version: "3"
services:
    user-auth-api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /app/node_modules
            - ./server:/app
        env_file:
            - server/.env
        ports: 
            - "9000:9000"
        depends_on:
            - mongo
    mongo:
        image: mongo
        ports:
            - "27017:27017"