version: "3"
services:
    api:
        build:
            dockerfile: Dockerfile.dev
            context: .
        volumes:
            - /app/node_modules
            - ./:/app
        env_file:
            - .env
        environment: :
            - MONGOHQ_TEST_URL=mongodb://mongo:27017/fot_db
        ports: 
            - "9000:9000"
        depends_on:
            - mongo
    mongo:
        image: mongo
        ports:
            - "27017:27017"